
install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# /usr/bin/clang is 3.4, lets override with modern one.
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
# - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_wait brew uninstall boost && travis_wait brew install boost --c++11 ; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v

addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - boost-latest
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - valgrind
    - libboost1.55-all-dev

language: cpp

compiler:
- clang
- gcc
os:
- linux
  #- osx # boost and C++11 and -stdlib=libc++ not working on macOS:x


# would require a rebuild (ABI not compatible)
matrix:
  exclude:
  - os: osx
    compiler: gcc


script: bash ./.travis_build_and_test.sh

